services:
  - type: web
    name: hub-starter-template
    env: node
    numInstances: 1
    buildCommand: npm install; npm run build
    startCommand: npm run start
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HOLAPLEX_AUTH_TOKEN
        sync: false
      - key: HOLAPLEX_PROJECT_ID
        sync: false
      - key: HOLAPLEX_DROP_ID
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: HOLAPLEX_WALLET_ASSET_TYPES
        value: SOL,MATIC
        sync: false
      - key: HOLAPLEX_API_ENDPOINT
        value: https://api.holaplex.com/graphql
      - key: DATABASE_URL
        fromDatabase:
          name: hub-starter-template
          property: connectionString
      - key: HOLAPLEX_PROJECT_ID
        sync: false
      - key: HOLAPLEX_A_DROP_ID
        sync: false
      - key: HOLAPLEX_B_DROP_ID
        sync: false
      - key: NEXT_PUBLIC_HOLAPLEX_VOTE_A_IMAGE
        sync: false
      - key: NEXT_PUBLIC_HOLAPLEX_VOTE_B_IMAGE
        sync: false

    autoDeploy: true

databases:
  - name: hub-starter-template
    ipAllowList: []
